name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
 group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
 cancel-in-progress: true

defaults:
 run:
   shell: bash

jobs:
 tests:
   runs-on:  ${{ matrix.os }}

   strategy:
     matrix:
       os: [ubuntu-latest, macos-latest, windows-latest]
       python-version: ["3.9"] #, "3.10", "3.11"] Don't need them. hatch env matrix will handle it
   steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch pre-commit
        hatch env create
    - name: Lint and typecheck
      run: |
        hatch run lint:lint-check

    - name: Install Docker CLI
      run: |
        if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          brew install --cask docker
        else
          sudo apt-get update
          sudo apt-get install -y docker-ce
        fi
    - name: Install bee-factory
      run: |
        npm install -g @ethersphere/bee-factory

    - name: Run Bee Factory
      run: |
        bee-factory start --detach 1.15.0-rc2
    - name: Run Tests
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]];
        then
          hatch run test:pyest --cache-clear
        else
          hatch run test:test_unit_only
        fi
